services:
  - type: web
    name: custom-churn
    runtime: python
    runtimeVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn auth:app --host 0.0.0.0 --port $PORT


